const db = require("./db");

// Helper: generate a date within the last N days
function daysAgo(n) {
  const d = new Date(Date.now() - n * 24 * 60 * 60 * 1000);
  return d.toISOString().slice(0, 19).replace("T", " ");
}

const jobs = [
  // ── Lebanese Market (Beirut & Tripoli) ──────────────────────────────
  { title: "Junior Software Engineer", company: "Murex", location: "Beirut, Lebanon", type: "full-time", description: "Join the capital markets technology leader. You will work on our MX.3 platform, developing modules for risk analytics and trade processing. Murex invests heavily in training fresh graduates — expect 3 months of onboarding, pair programming, and code reviews before owning features independently.", requirements: "Java, SQL, Data Structures, Algorithms, Git", salary: "$1,800 – $2,500/mo", posted_at: daysAgo(2) },
  { title: "Frontend Developer", company: "Anghami", location: "Beirut, Lebanon", type: "full-time", description: "Help build the music streaming experience for 70M+ users across MENA. You will develop responsive web interfaces, implement A/B experiments on the player UI, and collaborate closely with the design team to ship pixel-perfect features every sprint.", requirements: "React, TypeScript, CSS/Tailwind, REST API, Git", salary: "$1,500 – $2,200/mo", posted_at: daysAgo(1) },
  { title: "Backend Engineer", company: "Inkrypt", location: "Beirut, Lebanon", type: "full-time", description: "Work on blockchain-secured document verification APIs. You will design RESTful services in Node.js, integrate with Ethereum smart contracts, and write unit/integration tests. Our small team ships fast — you will own features end-to-end from DB schema to deployment.", requirements: "Node.js, Express, PostgreSQL, Docker, Solidity basics", salary: "$1,500 – $2,000/mo", posted_at: daysAgo(3) },
  { title: "Mobile Developer (React Native)", company: "Toters", location: "Beirut, Lebanon", type: "full-time", description: "Build and maintain the Toters delivery app used by hundreds of thousands across Lebanon and Iraq. You will implement new checkout flows, optimize app performance, and integrate real-time order tracking via WebSocket.", requirements: "React Native, JavaScript, Redux, Firebase, REST API", salary: "$1,400 – $2,000/mo", posted_at: daysAgo(5) },
  { title: "Data Analyst", company: "Blom Bank", location: "Beirut, Lebanon", type: "full-time", description: "Analyze transaction data to identify fraud patterns and generate risk reports for senior management. You will build dashboards in Power BI, write complex SQL queries, and present weekly findings to the compliance team.", requirements: "SQL, Excel, Power BI, Python basics, Statistics", salary: "$1,200 – $1,800/mo", posted_at: daysAgo(4) },
  { title: "UI/UX Designer", company: "Zaka", location: "Beirut, Lebanon", type: "full-time", description: "Design user interfaces for our AI-powered platforms. You will conduct user research, create wireframes and high-fidelity prototypes in Figma, run usability tests, and collaborate with engineers to ensure designs are implemented correctly.", requirements: "Figma, Adobe XD, User Research, Prototyping, Design Systems", salary: "$1,200 – $1,800/mo", posted_at: daysAgo(6) },
  { title: "DevOps Engineer", company: "Cedar Gate Technologies", location: "Beirut, Lebanon", type: "full-time", description: "Manage CI/CD pipelines for healthcare analytics products deployed on AWS. You will containerize microservices, set up monitoring and alerting with Prometheus/Grafana, and maintain Infrastructure as Code with Terraform.", requirements: "Docker, Kubernetes, AWS, Terraform, Linux, Jenkins", salary: "$2,000 – $3,000/mo", posted_at: daysAgo(7) },
  { title: "Full Stack Developer", company: "Roadster", location: "Beirut, Lebanon", type: "full-time", description: "Join Lebanon's leading e-commerce platform for automotive. Build new features across the React frontend and Node.js backend, optimize search performance, and integrate third-party payment gateways.", requirements: "React, Node.js, MongoDB, REST API, Git", salary: "$1,500 – $2,200/mo", posted_at: daysAgo(8) },
  { title: "QA Engineer", company: "Murex", location: "Beirut, Lebanon", type: "full-time", description: "Ensure quality of the MX.3 platform by writing automated test suites. You will design test plans, build Selenium/Cypress scripts, perform regression testing, and collaborate with developers to reproduce and fix bugs.", requirements: "Selenium, Cypress, Java, API Testing, Jira, SQL", salary: "$1,400 – $2,000/mo", posted_at: daysAgo(9) },
  { title: "IT Support Specialist", company: "LibanPost", location: "Beirut, Lebanon", type: "full-time", description: "Provide L1/L2 technical support across 70+ branches. Troubleshoot Windows workstations, manage Active Directory accounts, configure network printers, and escalate complex issues to the infrastructure team.", requirements: "Windows, Active Directory, Networking, Troubleshooting, Communication", salary: "$800 – $1,200/mo", posted_at: daysAgo(10) },
  { title: "Cybersecurity Analyst", company: "BankMed", location: "Beirut, Lebanon", type: "full-time", description: "Monitor SIEM dashboards for security incidents, conduct vulnerability assessments on internal systems, and assist in PCI-DSS compliance audits. You will also run phishing simulations and security awareness training for staff.", requirements: "SIEM, Networking, Linux, Vulnerability Scanning, Firewalls", salary: "$1,500 – $2,200/mo", posted_at: daysAgo(11) },
  { title: "Project Manager", company: "PwC Middle East", location: "Beirut, Lebanon", type: "full-time", description: "Lead digital transformation projects for banking and telecom clients in Lebanon. You will manage project timelines, coordinate between client stakeholders and development teams, and deliver status reports using Agile methodology.", requirements: "Agile, Scrum, Jira, Stakeholder Management, Communication", salary: "$2,000 – $3,000/mo", posted_at: daysAgo(12) },
  { title: "Network Engineer", company: "Ogero", location: "Beirut, Lebanon", type: "full-time", description: "Maintain and expand Lebanon's national broadband infrastructure. You will configure routers and switches, troubleshoot connectivity issues, plan capacity upgrades, and work with the NOC team on incident response.", requirements: "CCNA, TCP/IP, Routing, Switching, Firewalls, VPN", salary: "$1,200 – $1,800/mo", posted_at: daysAgo(13) },
  { title: "Marketing Coordinator", company: "Touch (Zain)", location: "Beirut, Lebanon", type: "full-time", description: "Coordinate digital marketing campaigns for one of Lebanon's two mobile operators. You will manage social media calendars, analyze campaign performance in Google Analytics, and collaborate with external agencies on creative assets.", requirements: "Social Media, Google Analytics, Content Strategy, Communication, Canva", salary: "$1,000 – $1,500/mo", posted_at: daysAgo(3) },
  { title: "ERP Consultant (SAP)", company: "Deloitte Lebanon", location: "Beirut, Lebanon", type: "full-time", description: "Configure and customize SAP modules for enterprise clients across MENA. You will gather business requirements, map them to SAP processes, perform system configuration, and support UAT and go-live phases.", requirements: "SAP FI/CO or MM, Business Processes, SQL, Communication", salary: "$2,000 – $3,000/mo", posted_at: daysAgo(14) },
  { title: "Intern – Software Development", company: "Murex", location: "Beirut, Lebanon", type: "part-time", description: "6-month paid internship for CS students. You will shadow senior engineers, contribute to internal tools, attend tech talks, and complete a capstone project. Strong performers receive full-time return offers.", requirements: "Java or Python, SQL basics, Git, Problem Solving", salary: "$500 – $800/mo", posted_at: daysAgo(1) },
  { title: "Junior Web Developer", company: "Jenius Social", location: "Beirut, Lebanon", type: "full-time", description: "Build websites and landing pages for regional clients in a fast-paced agency environment. You will implement responsive designs, integrate CMS platforms, and optimize page speed. Good opportunity for fresh graduates.", requirements: "HTML, CSS, JavaScript, React or Vue, Git", salary: "$800 – $1,200/mo", posted_at: daysAgo(15) },
  { title: "Database Administrator", company: "Byblos Bank", location: "Beirut, Lebanon", type: "full-time", description: "Manage Oracle and PostgreSQL databases supporting core banking applications. You will monitor performance, plan backups, tune slow queries, apply security patches, and coordinate with application teams during release windows.", requirements: "Oracle, PostgreSQL, SQL, Performance Tuning, Backup/Recovery", salary: "$1,500 – $2,200/mo", posted_at: daysAgo(16) },
  { title: "Business Analyst", company: "McKinsey & Company", location: "Beirut, Lebanon", type: "full-time", description: "Support consulting engagements by gathering requirements, building financial models in Excel, and translating business needs into actionable recommendations. You will work across industries including banking, telecom, and government.", requirements: "Excel, SQL, Requirements Analysis, Communication, PowerPoint", salary: "$2,500 – $3,500/mo", posted_at: daysAgo(17) },
  { title: "Graphic Designer", company: "Leo Burnett Beirut", location: "Beirut, Lebanon", type: "full-time", description: "Create visual assets for advertising campaigns across print, digital, and social media. You will work with art directors, follow brand guidelines, and produce deliverables under tight deadlines for regional clients.", requirements: "Photoshop, Illustrator, Figma, Typography, Branding", salary: "$1,000 – $1,500/mo", posted_at: daysAgo(18) },

  // ── Dubai / UAE ─────────────────────────────────────────────────────
  { title: "Senior Software Engineer", company: "Careem", location: "Dubai, UAE", type: "full-time", description: "Build scalable microservices for the Careem super-app handling millions of daily rides and deliveries. You will design APIs, optimize database queries, and mentor junior engineers. On-call rotation required.", requirements: "Go or Java, Microservices, PostgreSQL, Kubernetes, AWS", salary: "AED 18,000 – 25,000/mo", posted_at: daysAgo(2) },
  { title: "Product Manager", company: "Noon", location: "Dubai, UAE", type: "full-time", description: "Own the seller experience on noon.com. You will define the product roadmap, write PRDs, analyze conversion funnels, and work with engineering and design to ship features that improve seller onboarding and order management.", requirements: "Product Strategy, Data Analysis, Agile, SQL, Jira", salary: "AED 15,000 – 22,000/mo", posted_at: daysAgo(4) },
  { title: "Cloud Solutions Architect", company: "Amazon Web Services", location: "Dubai, UAE", type: "full-time", description: "Help enterprise customers across the Middle East design and migrate workloads to AWS. You will conduct architecture reviews, build proof-of-concept solutions, and deliver technical workshops on services like ECS, Lambda, and RDS.", requirements: "AWS (Solutions Architect certified preferred), Terraform, Networking, Docker, Python", salary: "AED 25,000 – 35,000/mo", posted_at: daysAgo(5) },
  { title: "Android Developer", company: "Talabat", location: "Dubai, UAE", type: "full-time", description: "Develop features for the Talabat food delivery app used across 8 countries. You will write clean Kotlin code, implement MVVM architecture, optimize app size and startup time, and integrate analytics SDKs.", requirements: "Kotlin, Android SDK, MVVM, Retrofit, Firebase, Git", salary: "AED 14,000 – 20,000/mo", posted_at: daysAgo(6) },
  { title: "Data Engineer", company: "Majid Al Futtaim", location: "Dubai, UAE", type: "full-time", description: "Build and maintain data pipelines processing retail transaction data from 300+ stores. You will use Spark for ETL, manage Airflow DAGs, and ensure data quality for the BI and data science teams.", requirements: "Python, SQL, Apache Spark, Airflow, AWS or Azure", salary: "AED 16,000 – 22,000/mo", posted_at: daysAgo(7) },
  { title: "QA Automation Engineer", company: "Emirates NBD", location: "Dubai, UAE", type: "full-time", description: "Build automated test frameworks for digital banking products. You will write end-to-end tests with Cypress, API tests with Postman/Newman, and integrate test suites into the CI/CD pipeline.", requirements: "Cypress, JavaScript, API Testing, Postman, Jenkins, Git", salary: "AED 12,000 – 18,000/mo", posted_at: daysAgo(8) },
  { title: "Site Reliability Engineer", company: "Dubizzle (EMPG)", location: "Dubai, UAE", type: "full-time", description: "Keep dubizzle's classified platform running at 99.9% uptime. You will manage Kubernetes clusters, set up monitoring with Datadog, automate incident response, and conduct post-mortems.", requirements: "Linux, Docker, Kubernetes, Monitoring (Datadog/Prometheus), Python", salary: "AED 18,000 – 25,000/mo", posted_at: daysAgo(9) },
  { title: "Blockchain Developer", company: "DMCC", location: "Dubai, UAE", type: "full-time", description: "Develop smart contracts for the DMCC Tradeflow platform. You will write and audit Solidity contracts, build Web3 frontend integrations, and work with the compliance team on KYC/AML token standards.", requirements: "Solidity, Ethereum, JavaScript, Node.js, Web3.js, Hardhat", salary: "AED 20,000 – 30,000/mo", posted_at: daysAgo(10) },
  { title: "Scrum Master", company: "Etisalat (e&)", location: "Dubai, UAE", type: "full-time", description: "Facilitate Agile ceremonies for 3 cross-functional squads building the e& digital platform. You will coach teams on Scrum practices, remove blockers, track velocity, and drive continuous improvement.", requirements: "Scrum (CSM preferred), Agile, Jira, Facilitation, Communication", salary: "AED 14,000 – 20,000/mo", posted_at: daysAgo(11) },

  // ── Riyadh / Saudi Arabia ───────────────────────────────────────────
  { title: "Full Stack Developer", company: "STC", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Build internal tools and customer-facing portals for Saudi Arabia's largest telecom. You will develop React frontends and Spring Boot APIs, integrate with Oracle databases, and deploy to on-prem Kubernetes clusters.", requirements: "React, Java/Spring Boot, Oracle, Docker, Git", salary: "SAR 12,000 – 18,000/mo", posted_at: daysAgo(3) },
  { title: "Cybersecurity Engineer", company: "NEOM", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Secure infrastructure for the NEOM smart city project. You will conduct penetration tests, design zero-trust architectures, implement SIEM rules, and respond to security incidents across cloud and IoT environments.", requirements: "Penetration Testing, SIEM, Cloud Security, Linux, Python", salary: "SAR 18,000 – 28,000/mo", posted_at: daysAgo(5) },
  { title: "Machine Learning Engineer", company: "SDAIA", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Develop and deploy ML models for national data analytics initiatives under Saudi Vision 2030. You will train NLP models for Arabic text, build prediction pipelines, and serve models via FastAPI.", requirements: "Python, TensorFlow/PyTorch, NLP, FastAPI, Docker, SQL", salary: "SAR 15,000 – 25,000/mo", posted_at: daysAgo(7) },
  { title: "Systems Administrator", company: "Aramco Digital", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Manage Windows and Linux server farms supporting critical oil & gas applications. You will handle patching, capacity planning, AD management, and coordinate with the network team during maintenance windows.", requirements: "Linux, Windows Server, Networking, Bash, Virtualization (VMware)", salary: "SAR 10,000 – 15,000/mo", posted_at: daysAgo(12) },
  { title: "Embedded Systems Engineer", company: "Advanced Electronics Company", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Develop firmware for defense and communications IoT devices. You will write C/C++ for ARM microcontrollers, interface with sensors via SPI/I2C, and perform hardware-in-the-loop testing.", requirements: "C, C++, Embedded Systems, RTOS, ARM Microcontrollers", salary: "SAR 12,000 – 18,000/mo", posted_at: daysAgo(14) },

  // ── Remote / International ──────────────────────────────────────────
  { title: "Frontend Engineer (React)", company: "Shopify", location: "Remote", type: "remote", description: "Build merchant-facing e-commerce tools used by millions of store owners. You will develop React components, write unit tests with Jest, optimize bundle size, and participate in design system contributions. Fully remote with async-first culture.", requirements: "React, TypeScript, GraphQL, Jest, CSS-in-JS, Git", salary: "$4,000 – $6,000/mo", posted_at: daysAgo(1) },
  { title: "Backend Engineer (Python)", company: "Stripe", location: "Remote", type: "remote", description: "Build payment infrastructure APIs that process billions of dollars. You will design distributed systems, write Python services, manage database migrations, and participate in on-call rotation for production incidents.", requirements: "Python, Django or FastAPI, PostgreSQL, Redis, Docker, REST API", salary: "$5,000 – $8,000/mo", posted_at: daysAgo(2) },
  { title: "Machine Learning Engineer", company: "Hugging Face", location: "Remote", type: "remote", description: "Contribute to open-source ML tooling used by researchers worldwide. You will fine-tune transformer models, optimize inference performance, write documentation, and engage with the community on GitHub.", requirements: "Python, PyTorch, Transformers, NLP, Docker, Git", salary: "$5,000 – $8,000/mo", posted_at: daysAgo(3) },
  { title: "iOS Developer", company: "Duolingo", location: "Remote", type: "remote", description: "Build gamified language-learning features for 50M+ monthly active users. You will write Swift code following MVVM, implement animations, A/B test UI variants, and optimize app performance.", requirements: "Swift, UIKit/SwiftUI, Xcode, CoreData, REST API, Git", salary: "$4,500 – $7,000/mo", posted_at: daysAgo(4) },
  { title: "DevOps / Platform Engineer", company: "GitLab", location: "Remote", type: "remote", description: "Improve GitLab's own CI/CD infrastructure. You will manage Kubernetes clusters on GCP, build Terraform modules, automate deployment pipelines, and contribute to GitLab's open-source platform. All-remote company.", requirements: "Kubernetes, Terraform, GCP or AWS, Linux, Go or Python", salary: "$5,000 – $8,000/mo", posted_at: daysAgo(5) },
  { title: "Technical Writer", company: "Twilio", location: "Remote", type: "part-time", description: "Write and maintain developer documentation for Twilio's APIs. You will create tutorials, update API reference docs, build code samples in multiple languages, and collaborate with engineering to document new features.", requirements: "Technical Writing, Markdown, API Documentation, Git, JavaScript or Python", salary: "$2,000 – $3,000/mo", posted_at: daysAgo(6) },
  { title: "Data Analyst", company: "Canva", location: "Remote", type: "remote", description: "Analyze product usage data to drive growth decisions. You will build dashboards in Looker, write SQL queries against BigQuery, run A/B test analyses, and present insights to product managers.", requirements: "SQL, Python, Looker or Power BI, A/B Testing, Statistics", salary: "$3,500 – $5,500/mo", posted_at: daysAgo(8) },
  { title: "PHP/Laravel Developer", company: "Automattic (WordPress)", location: "Remote", type: "remote", description: "Build and maintain WordPress.com features serving 400M+ monthly visitors. You will write PHP/Laravel code, optimize MySQL queries, and ship code daily in a distributed, async team.", requirements: "PHP, Laravel, MySQL, JavaScript, REST API, Git", salary: "$3,000 – $5,000/mo", posted_at: daysAgo(9) },
  { title: "Game Developer (Unity)", company: "Ubisoft", location: "Remote", type: "full-time", description: "Develop game mechanics and systems for mobile titles. You will write C# scripts in Unity, implement UI flows, optimize memory usage, and collaborate with artists and designers in a cross-functional squad.", requirements: "Unity, C#, Game Design, 3D Math, Git", salary: "$3,500 – $5,500/mo", posted_at: daysAgo(10) },
  { title: "SEO Specialist", company: "HubSpot", location: "Remote", type: "part-time", description: "Improve organic search rankings for HubSpot's marketing blog reaching 7M+ monthly readers. You will perform keyword research, optimize on-page SEO, analyze ranking changes, and coordinate with the content team.", requirements: "SEO, Google Analytics, Search Console, Content Strategy, HTML basics", salary: "$1,500 – $2,500/mo", posted_at: daysAgo(11) },
  { title: "Content Creator / Social Media", company: "Notion", location: "Remote", type: "part-time", description: "Create short-form video content and social media posts showcasing Notion workflows. You will plan content calendars, shoot/edit videos, engage with the community, and track engagement metrics.", requirements: "Video Editing, Social Media, Creativity, Canva, Communication", salary: "$1,200 – $2,000/mo", posted_at: daysAgo(13) },
  { title: "Customer Success Engineer", company: "Vercel", location: "Remote", type: "remote", description: "Help developers troubleshoot Next.js deployments and build configurations. You will debug production issues, write support articles, escalate bugs to engineering, and contribute to the Vercel docs.", requirements: "Next.js, React, Node.js, Git, Communication, Debugging", salary: "$3,000 – $5,000/mo", posted_at: daysAgo(14) },
  { title: "AI Research Assistant", company: "Google DeepMind", location: "Remote", type: "part-time", description: "Assist senior researchers with experiment tracking, literature reviews, and benchmark evaluation. You will run training scripts, analyze results in Jupyter notebooks, and help prepare figures for paper submissions.", requirements: "Python, Machine Learning, PyTorch, Research Methods, LaTeX", salary: "$2,000 – $3,500/mo", posted_at: daysAgo(15) },
  { title: "HR Coordinator", company: "Remote.com", location: "Remote", type: "remote", description: "Support global hiring operations across 60+ countries. You will coordinate onboarding for new hires, manage HRIS records, answer employee queries, and assist with payroll processing.", requirements: "HR Systems, Communication, Excel, Organization, English", salary: "$2,000 – $3,000/mo", posted_at: daysAgo(16) },

  // ── More Lebanon & MENA mix ─────────────────────────────────────────
  { title: "Python Developer", company: "CERN (via LAU partnership)", location: "Beirut, Lebanon", type: "part-time", description: "Contribute to data analysis tools for particle physics research as part of a university collaboration with CERN. You will write Python scripts for ROOT framework data processing and build visualization dashboards.", requirements: "Python, NumPy, Pandas, Data Visualization, Git", salary: "$1,000 – $1,500/mo", posted_at: daysAgo(4) },
  { title: "Software Engineer – Fintech", company: "Sarwa", location: "Dubai, UAE", type: "full-time", description: "Build the investment platform powering wealth management for retail investors across the Gulf. You will develop microservices in Python, integrate with brokerage APIs, and ensure regulatory compliance.", requirements: "Python, FastAPI, PostgreSQL, Docker, AWS, REST API", salary: "AED 15,000 – 22,000/mo", posted_at: daysAgo(6) },
  { title: "Technical Support Engineer", company: "Alfa (Orascom)", location: "Beirut, Lebanon", type: "full-time", description: "Provide L2 support for Lebanon's mobile network infrastructure. You will troubleshoot OSS/BSS platforms, analyze call drop patterns, coordinate with Ericsson vendor teams, and document resolution procedures.", requirements: "Networking, Linux, SQL, Telecom basics, Communication", salary: "$1,000 – $1,500/mo", posted_at: daysAgo(8) },
  { title: "React Native Developer", company: "Kitopi", location: "Dubai, UAE", type: "full-time", description: "Build the kitchen operations app for the world's leading cloud kitchen platform. You will develop cross-platform features, integrate real-time order feeds, and optimize app performance for low-end devices.", requirements: "React Native, TypeScript, Redux, REST API, Firebase", salary: "AED 13,000 – 18,000/mo", posted_at: daysAgo(9) },
  { title: "Accounting Software Developer", company: "Bayt.com", location: "Dubai, UAE", type: "full-time", description: "Develop and maintain internal accounting and invoicing tools. You will build REST APIs in Node.js, create React admin panels, integrate with payment gateways, and ensure PCI compliance.", requirements: "Node.js, React, PostgreSQL, REST API, Git", salary: "AED 12,000 – 17,000/mo", posted_at: daysAgo(11) },
  { title: "Junior Data Scientist", company: "Aramco Digital", location: "Riyadh, Saudi Arabia", type: "full-time", description: "Apply machine learning to predict equipment failures in oil & gas operations. You will clean sensor data, build classification models, evaluate performance, and present results to operations managers.", requirements: "Python, Scikit-learn, Pandas, SQL, Statistics", salary: "SAR 10,000 – 15,000/mo", posted_at: daysAgo(13) },
  { title: "Cloud Engineer", company: "Zain Group", location: "Remote", type: "remote", description: "Manage multi-cloud infrastructure for Zain's digital services across 8 markets. You will provision resources with Terraform, monitor costs, implement security best practices, and support production deployments.", requirements: "AWS, Azure, Terraform, Docker, Linux, Python", salary: "$3,000 – $4,500/mo", posted_at: daysAgo(15) },
  { title: "Product Designer", company: "Fetchr", location: "Dubai, UAE", type: "full-time", description: "Design delivery experiences for a logistics startup disrupting last-mile in the Gulf. You will lead user research, design mobile app flows, create prototypes, and validate with driver and customer segments.", requirements: "Figma, User Research, Mobile Design, Prototyping, Design Thinking", salary: "AED 14,000 – 20,000/mo", posted_at: daysAgo(17) },
  { title: "Digital Marketing Specialist", company: "Anghami", location: "Beirut, Lebanon", type: "full-time", description: "Plan and execute paid acquisition campaigns across Google Ads, Meta, and TikTok to grow Anghami's subscriber base. You will manage budgets, run A/B tests on creatives, and report ROAS weekly.", requirements: "Google Ads, Meta Ads, Analytics, Excel, Communication", salary: "$1,200 – $1,800/mo", posted_at: daysAgo(2) },
  { title: "Solutions Architect", company: "Microsoft", location: "Dubai, UAE", type: "full-time", description: "Design Azure-based solutions for enterprise clients in the Middle East. You will conduct workshops, create architecture blueprints, build demos, and support pre-sales engagements across government and finance verticals.", requirements: "Azure (AZ-305 preferred), Networking, Docker, PowerShell, Communication", salary: "AED 22,000 – 32,000/mo", posted_at: daysAgo(19) },
];

// Clear existing jobs before seeding
db.prepare("DELETE FROM jobs").run();

const insert = db.prepare(`
  INSERT INTO jobs (title, company, location, type, description, requirements, salary, posted_at)
  VALUES (@title, @company, @location, @type, @description, @requirements, @salary, @posted_at)
`);

const insertMany = db.transaction((jobList) => {
  for (const job of jobList) {
    insert.run(job);
  }
});

insertMany(jobs);
console.log(`Seeded ${jobs.length} jobs into the database.`);
